### PR TITLE
wrap/unwrap domains

### PR DESCRIPTION
**Pull request by wosleyv**

### CODE REVIEW

**Comment by SanjaySargam** [comment]
@wosleyv Hey Hii Can you please guide me setting up and run this project locally 
I am not able to do

**Comment by dr497** [comment]
@wosleyv Thanks a lot for opening this PR, I will review in the coming days.

@SanjaySargam What error are you getting?

**Comment by SanjaySargam** [comment]
@dr497 I cloned the repo 
What are the commands which I need to run and which is the best editor - VS studio or Android Studio?
Will you please guide me step by step

**Comment by dr497** [comment]
@SanjaySargam If your issue is unrelated to this pull request please open a separate issue or on join our Discord so we can keep this discussion focused on the content of the PR

**Comment by SanjaySargam** [comment]
Ok

**Comment by dr497** [comment]
[@wosleyv](https://github.com/wosleyv) The PR looks great. However, I've noticed a few minor areas that could be improved:

- When wrapping (and unwrapping) the success modal overlaps the initial modal resulting in 2 modals being opened at once. Once the tx is confirmed, the initial modal should be closed.
- The PR does not support internationalization, can you rebase your branch on master and then you wrap all `Text` into `Trans` macros, for error modals messages you can use `t`.
- When unwrapping a domain, you first need to run the [withdraw tokens instruction](https://github.com/Bonfida/name-tokenizer/blob/master/js/src/bindings.ts#L254) to handle cases where funds have been sent by mistake to the PDA escrow instead of the NFT owner. Below is a code snippet you can use

```ts
import { TransactionInstruction, PublicKey, Connection } from "@solana/web3.js";
import { getDomainKeySync } from "@bonfida/spl-name-service";
import {
  NAME_TOKENIZER_ID,
  NftRecord,
  MINT_PREFIX,
  withdrawTokens,
  redeemNft,
} from "@bonfida/name-tokenizer";
import {
  TOKEN_PROGRAM_ID,
  AccountLayout,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountInstruction,
  createCloseAccountInstruction,
  getAssociatedTokenAddressSync,
  NATIVE_MINT,
} from "@solana/spl-token";

const checkAccountExists = async (
  connection: Connection,
  key: PublicKey
): Promise<boolean> => {
  const info = await connection.getAccountInfo(key);
  if (!!info?.data) {
    return true;
  }
  return false;
};

export const redeemSol = async (
  connection: Connection,
  recordKey: PublicKey,
  publicKey: PublicKey,
  tokenAccountLen: number,
  nftMint: PublicKey
) => {
  const instructions: TransactionInstruction[] = [];
  const recordInfo = await connection.getAccountInfo(recordKey);
  if (!recordInfo) {
    throw new Error("Record info not found");
  }
  const minRent = await connection.getMinimumBalanceForRentExemption(
    recordInfo?.data.length
  );
  if (
    recordInfo.lamports > minRent &&
    tokenAccountLen === 0 // If > 0 the native SOL will be withdrawn in another ix
  ) {
    const ataDestination = await getAssociatedTokenAddress(
      NATIVE_MINT,
      publicKey
    );
    if (!(await checkAccountExists(connection, ataDestination))) {
      instructions.push(
        createAssociatedTokenAccountInstruction(
          publicKey,
          ataDestination,
          publicKey,
          NATIVE_MINT
        )
      );
    }
    const ataSource = await getAssociatedTokenAddress(
      NATIVE_MINT,
      recordKey,
      true
    );
    const createAta = createAssociatedTokenAccountInstruction(
      publicKey,
      ataSource,
      recordKey,
      NATIVE_MINT
    );
    const withdrawIx = await withdrawTokens(
      nftMint,
      NATIVE_MINT,
      publicKey,
      recordKey,
      NAME_TOKENIZER_ID
    );
    instructions.push(createAta, ...withdrawIx);
  }
  return instructions;
};

export const unwrap = async (
  connection: Connection,
  domain: string,
  publicKey: PublicKey
) => {
  const instructions: TransactionInstruction[] = [];
  const { pubkey } = getDomainKeySync(domain);
  const [recordKey] = await NftRecord.findKey(pubkey, NAME_TOKENIZER_ID);
  const [mint] = await PublicKey.findProgramAddress(
    [MINT_PREFIX, pubkey.toBuffer()],
    NAME_TOKENIZER_ID
  );

  const recordTokenAccounts = await connection.getTokenAccountsByOwner(
    recordKey,
    { programId: TOKEN_PROGRAM_ID }
  );

  for (let tokenAcc of recordTokenAccounts.value) {
    const des = AccountLayout.decode(tokenAcc.account.data);
    const ata = await getAssociatedTokenAddress(des.mint, publicKey);
    if (!(await checkAccountExists(connection, ata))) {
      const ix = createAssociatedTokenAccountInstruction(
        publicKey,
        ata,
        publicKey,
        des.mint
      );
      instructions.push(ix);
    }
    const ix = await withdrawTokens(
      mint,
      des.mint,
      publicKey,
      recordKey,
      NAME_TOKENIZER_ID
    );
    instructions.push(...ix);
  }
  const withdrawNativeSol = await redeemSol(
    connection,
    recordKey,
    publicKey,
    recordTokenAccounts.value.length,
    mint
  );
  instructions.push(...withdrawNativeSol);

  const ix = await redeemNft(pubkey, publicKey, NAME_TOKENIZER_ID);
  instructions.push(...ix);

  // Close token account
  const ata = getAssociatedTokenAddressSync(mint, publicKey);
  const ix_close = createCloseAccountInstruction(ata, publicKey, publicKey);
  instructions.push(ix_close);

  return instructions;
};
```

**Comment by wosleyv** [comment]
> * When unwrapping a domain, you first need to run the [withdraw tokens instruction](https://github.com/Bonfida/name-tokenizer/blob/master/js/src/bindings.ts#L254) to handle cases where funds have been sent by mistake to the PDA escrow instead of the NFT owner. Below is a code snippet you can use

I think the unwrap fn is already doing this: https://github.com/wosleyv/sns-manager/blob/wrap-domain/src/utils/unwrap/index.tsx
so I just created the [wrap fn](https://github.com/Bonfida/sns-manager/pull/11/files#diff-bf53f2878507c447a5c715f9930f9636da20211c8157fedda16665ba6ec7a669)

**Comment by dr497** [comment]
@wosleyv You are right, good catch! The current PR looks good to me

**Pull request merged**
